rateLimits:
  # banned because deprecated
  /api/scan/v1/updates:
    name: v1-updates
    type: banned

  # banned because deprecated
  /api/scan/v0/amulet-config-for-round:
    name: amulet-config-for-round
    type: banned
