# Copyright (c) 2024 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

imageRepo: "ghcr.io/digital-asset/decentralized-canton-sync/docker"
docs:
  imageName: "docs"
gcsProxy:
  imageName: "gcs-proxy"

enableGcsProxy: false

# should stakater reloader annotation be added (note: reloader needs to be installed separately)
enableReloader: true

# k8s affinity for all deployed pods (optional)
# affinity:

# k8s nodeSelector for all deployed pods (optional)
# nodeSelector:

# k8s tolerations for all deployed pods (optional)
# tolerations:
service:
  http:
    port: 80


securityContexts:
  pod:
    security_context_profile: pod_security_context
  containers:
    docs:
      security_context_profile: ui_security_context
      capabilities:
        drop:
          - ALL
        add:
          - NET_BIND_SERVICE # Added so the application can bind to 443
    gcsProxy:
      security_context_profile: app_security_context
