create table sequencer_traffic_summary_store
(
    -- Primary key for the table
    row_id                      bigint generated by default as identity,
    -- The time when this row was inserted, used for debugging and monitoring
    ingested_at                 timestamptz not null default now(),
    -- History identifier for update history partitioning
    history_id                  bigint not null,
    -- Migration identifier for domain migrations
    migration_id                bigint not null,
    -- Domain identifier
    domain_id                   text not null,
    -- Time as of which the message was sequenced
    sequencing_time             bigint not null,
    -- The sender of the message (typically the participant id of the validator node)
    sender                      text not null,
    -- Total traffic cost of the message paid by the sender
    total_traffic_cost          bigint not null,
    -- Envelope data as JSONB array: [{"traffic_cost": 100, "view_hashes": ["h1", "h2"]}, ...]
    -- Using JSONB because PostgreSQL 2D arrays require uniform dimensions,
    -- but each envelope can have a different number of view_hashes
    envelopes                   jsonb not null,
    constraint sequencer_traffic_summary_store_pkey primary key (row_id),
    -- Unique constraint for deduplication during ingestion
    constraint sequencer_traffic_summary_unique unique (history_id, sequencing_time, sender)
);

-- Index for efficient querying by history, migration and sequencing time
create index sequencer_traffic_hi_mi_st on sequencer_traffic_summary_store (history_id, migration_id, sequencing_time);

-- GIN index for efficient view_hash lookups in correlation queries via JSONB path
create index sequencer_traffic_envelopes_gin on sequencer_traffic_summary_store using gin (envelopes jsonb_path_ops);
