# Copyright (c) 2024 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

{{- define "configmap-content-static" }}
deploymentInfo:
  network: {{ .Values.deploymentDetails.network | quote }}
  sv:
    version: {{ .Values.deploymentDetails | dig "sv" "version" $.Chart.Version | quote }}
  configDigest:
    {{- with .Values.deploymentDetails.configDigest }}
    allowed-ip-ranges: {{ printf "%s:%s" .allowedIpRanges.type .allowedIpRanges.value | quote }}
    approved-sv-id-values: {{ printf "%s:%s" .approvedSvIdentities.type .approvedSvIdentities.value | quote }}
    {{- end }}
  synchronizer:
    {{- with .Values.deploymentDetails.synchronizer }}
    current:
      version: {{ .current.version | default $.Chart.Version | quote }}
      migrationId: {{ .current.migrationId }}
      chainIdSuffix: {{ .current.chainIdSuffix | quote }}
      synchronizerSerialId: {{ .current.synchronizerSerialId }}
    successor:
      {{- if .successor }}
      version: {{ .successor.version | quote }}
      migrationId: {{ .successor.migrationId }}
      chainIdSuffix: {{ .successor.chainIdSuffix | quote }}
      synchronizerSerialId: {{ .successor.synchronizerSerialId }}
      {{- end }}
    legacy:
      {{- if .legacy }}
      version: {{ .legacy.version | quote }}
      migrationId: {{ .legacy.migrationId }}
      chainIdSuffix: {{ .legacy.chainIdSuffix | quote }}
      synchronizerSerialId: {{ .legacy.synchronizerSerialId }}
      {{- end }}
    {{- end }}
{{- end }}

{{- if .Values.deploymentDetails }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-content-static
  namespace: {{ .Release.Namespace }}
data:
  index.html: {{ include "configmap-content-static" . | fromYaml | toJson | quote }}
{{- end }}
