#nginxImage: nginx:<version>@sha256:<digest>
#updaterImage: registry.gitlab.com/gitlab-ci-utils/curl-jq:<version>@sha256:<digest>

runtimeDetails:
  synchronizerSerialId: SERIAL_ID
  #scanUrl: "http://scan-app:5012"

deploymentDetails:  # optional, exposes static configuration under path /
  network: TARGET_CLUSTER  # One of "main", "test" or "dev"
  configDigest:
    allowedIpRanges:
      type: "md5"
      value: MD5_HASH_OF_ALLOWED_IP_RANGES
    approvedSvIdentities:
      type: "md5"
      value: MD5_HASH_OF_APPROVED_SV_IDENTITIES
  synchronizer:
    current:
      chainIdSuffix: CHAIN_ID_SUFFIX
      migrationId: MIGRATION_ID  # DevNet: 1, TestNet: 1, MainNet: 4
      synchronizerSerialId: SERIAL_ID
      #version: SYNCHRONIZER_VERSION
    #successor:  # Configure this when successor synchronizer is enabled
    #  chainIdSuffix: STAGING_SYNCHRONIZER_CHAIN_ID_SUFFIX
    #  migrationId: MIGRATION_ID  # DevNet: 1, TestNet: 1, MainNet: 4
    #  synchronizerSerialId: STAGING_SYNCHRONIZER_SERIAL_ID
    #  version: STAGING_SYNCHRONIZER_VERSION
    #legacy:  # Configure this when legacy synchronizer is enabled
    #  chainIdSuffix: LEGACY_SYNCHRONIZER_CHAIN_ID_SUFFIX
    #  migrationId: MIGRATION_ID  # DevNet: 1, TestNet: 1, MainNet: 4
    #  synchronizerSerialId: LEGACY_SYNCHRONIZER_SERIAL_ID
    #  version: LEGACY_SYNCHRONIZER_VERSION

#istioVirtualService:  # optional, configures the Istio VirtualService for routing
#  host: "info.example.com"
#  gateway: "istio-gateway-example"
