# Copyright (c) 2024 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

profiles:
  pod_security_context:
    seccompProfile:
      type: RuntimeDefault

  app_security_context:
    runAsNonRoot: true
    runAsUser: 1001
    runAsGroup: 1001
    allowPrivilegeEscalation: false
    privileged: false
    capabilities:
      drop:
        - ALL

  ui_security_context:
    # TODO(DACH-NY/canton-network-internal#5948) Support runAsNonRoot
    allowPrivilegeEscalation: false
    privileged: false
    capabilities:
      drop:
        - ALL

  persistent_security_context:
    runAsNonRoot: true
    runAsUser: 1001
    runAsGroup: 1001
    allowPrivilegeEscalation: false
    privileged: false
    capabilities:
      drop:
        - ALL
